In [1]:
import numpy as np

## 1. DataTpes & Attributes

In [5]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
print(a1, type(a1))

[1 2 3] <class 'numpy.ndarray'>


In [12]:
print(type(a1))
print(a1.dtype)
print(a1.shape) ##  (number in column, number in row)
print(a1.ndim)

<class 'numpy.ndarray'>
int64
(3,)
1


In [14]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [7]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [11]:
print(type(a2))
print(a2.dtype)
print(a2.shape) ##  (number in column, number in row)
print(a2.ndim)

<class 'numpy.ndarray'>
float64
(2, 3)
2


In [15]:
print(type(a3))
print(a3.dtype)
print(a3.shape)
print(a3.ndim)

<class 'numpy.ndarray'>
int64
(2, 3, 3)
3


In [17]:
a4 = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]]])

In [18]:
print(type(a4))
print(a4.dtype)
print(a4.shape)
print(a4.ndim)

<class 'numpy.ndarray'>
int64
(2, 2, 3)
3


In [19]:
#Create a DataFrame from NumPy array
import pandas as pd

In [23]:
print(a2)

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [21]:
df2 = pd.DataFrame(a2)
df2

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [24]:
# upto 2 dimensional array
# df3 = pd.DataFrame(a3)
# df